repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      # Run the Ruff linter and automatically fix safe errors
      - id: ruff
        args: [ --fix ]
      # Run the Ruff formatter
      - id: ruff-format